name: Semgrep

on:
  workflow_dispatch: {}     # Manually trigger from GitHub Actions page
  pull_request: {}          # Run Semgrep for every Pull Request
  push:
    branches:
      - main                # Run for commits to main branch
      - master              # Run for commits to master branch
    paths:
      - .github/workflows/semgrep.yml   # Run when this workflow file changes
  schedule:
    - cron: '12 15 * * *'   # Run daily at random time (3:12 PM UTC)

jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-latest  # GitHub Actions runner
    permissions:
      contents: read
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: semgrep/semgrep   # Run inside official Semgrep container
    if: (github.actor != 'dependabot[bot]')

    steps:
      - uses: actions/checkout@v4
      - run: semgrep ci
